# Generated by Django 4.1 on 2022-09-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('JogadorId', models.AutoField(primary_key=True, serialize=False)),
                ('JogadorNome', models.CharField(max_length=100)),
                ('JogadorForca', models.IntegerField()),
            ],
        ),
    ]
